### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by hillaryj — APPROVED** [review]
⚡

**Comment by jsf9k** [comment]
@dav3r - is there a reason that this repository does not inherit from [cisagov/skeleton-docker](https://github.com/cisagov/skeleton-docker)?

**Comment by dav3r** [comment]
> @dav3r - is there a reason that this repository does not inherit from [cisagov/skeleton-docker](https://github.com/cisagov/skeleton-docker)?

I think this repo predates [cisagov/skeleton-docker](https://github.com/cisagov/skeleton-docker) - we should be able to make that change.

**Review by jsf9k — APPROVED** [review]
Let's approve this one, then make a separate PR for changing the upstream to skeleton-docker.  I created #14 to remind us to do this.

**Review by dav3r — APPROVED** [review]
👍

**Pull request merged**
